2023-03-13 16:12:11.607026: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:From /home/chadwiley/research/wofs_40dbz/wofs_ml/unet/hparam_wofs_ml.py:239: load (from tensorflow.python.data.experimental.ops.io) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.load(...)` instead.
W0313 16:13:21.601990 47679145459456 deprecation.py:350] From /home/chadwiley/research/wofs_40dbz/wofs_ml/unet/hparam_wofs_ml.py:239: load (from tensorflow.python.data.experimental.ops.io) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.load(...)` instead.
Traceback (most recent call last):
  File "/home/chadwiley/research/wofs_40dbz/wofs_ml/unet/hparam_wofs_ml.py", line 393, in <module>
    app.run(main)
  File "/home/chadwiley/miniconda3/envs/tf/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/chadwiley/miniconda3/envs/tf/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/chadwiley/research/wofs_40dbz/wofs_ml/unet/hparam_wofs_ml.py", line 388, in main
    run_all(logdir=logdir, verbose=True)
  File "/home/chadwiley/research/wofs_40dbz/wofs_ml/unet/hparam_wofs_ml.py", line 352, in run_all
    data = prepare_data()
  File "/home/chadwiley/research/wofs_40dbz/wofs_ml/unet/hparam_wofs_ml.py", line 239, in prepare_data
    train_ds = tf.data.experimental.load('/ourdisk/hpc/ai2es/chadwiley/patches/data_64/tf_ds/train_maxfilter.tf')
  File "/home/chadwiley/miniconda3/envs/tf/lib/python3.10/site-packages/tensorflow/python/util/deprecation.py", line 357, in new_func
    return func(*args, **kwargs)
  File "/home/chadwiley/miniconda3/envs/tf/lib/python3.10/site-packages/tensorflow/python/data/experimental/ops/io.py", line 167, in load
    return dataset_ops.Dataset.load(path, element_spec, compression, reader_func)
  File "/home/chadwiley/miniconda3/envs/tf/lib/python3.10/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1835, in load
    return load_op.load(
  File "/home/chadwiley/miniconda3/envs/tf/lib/python3.10/site-packages/tensorflow/python/data/ops/load_op.py", line 36, in load
    return _LoadDataset(path, element_spec, compression, reader_func)
  File "/home/chadwiley/miniconda3/envs/tf/lib/python3.10/site-packages/tensorflow/python/data/ops/load_op.py", line 57, in __init__
    encoded_spec = f.read()
  File "/home/chadwiley/miniconda3/envs/tf/lib/python3.10/site-packages/tensorflow/python/lib/io/file_io.py", line 114, in read
    self._preread_check()
  File "/home/chadwiley/miniconda3/envs/tf/lib/python3.10/site-packages/tensorflow/python/lib/io/file_io.py", line 76, in _preread_check
    self._read_buf = _pywrap_file_io.BufferedInputStream(
tensorflow.python.framework.errors_impl.NotFoundError: /ourdisk/hpc/ai2es/chadwiley/patches/data_64/tf_ds/train_maxfilter.tf/dataset_spec.pb; No such file or directory
slurmstepd: error: acct_gather_profile/influxdb _send_data: curl_easy_perform failed to send data (discarded). Reason: Couldn't resolve host name
